language: node_js
node_js:
- node
- '8'
- '10'
sudo: false
cache:
  directories:
  - node_modules
deploy:
  node_js: 8
  provider: npm
  skip_cleanup: true
  email: honza@hommer.cz
  api_key:
    secure: LNJBUmRRpchCdn3EsiQwOdmXKcnU45RqSP6nOmuzsq48w6D9gl5LHCF2MivJ7+B0A97W3C8eX8aUixveOv9hc6kD/+fJAlq95uLZ0TqcjzZuWOTYVyPi2mk8pJ+k8pCpC9bTLWTo8a1h5wMrqU1V3y77f4729fG5PbeMUKqPF44C0d6qCTvGNiPzYGE9hv5P4fg7TFWj3TSxWemcygAqYNnV1n4QRD7pV7BjpNRZ0HQXTOko3J6KC52mji0mPJ9M+qi3n4z3x7SugxE2CGHqa8HnW+S324ssbWH/Xavijpq8bNm2Vht9nSo/vCHrW3e+lU8E5+fPacM+QPDWTlrr78Um4JoOd/6/X6qPzeeEwASdBgyOh+f0610G8BIvaXIncvRbjciQ2sq4GOlCQH0julrMXdQZcpwP0JPrkvGBbakQdXeEzl+1fHt9/LnUwpkTpYFm0Zf3/w28A7uVFD1SL1hHMeJMwzbmxA56VNH9Wm9gSMAPWoXThvU8HVhE0BTkhHkvnIFIiJsBZ3l69Je7reWX/n+NLxEW1+vFHZ/zUGwXxTzGj1j+EzITesOE/AYGnLtqF7mIz01q0JP/uosDMPHx31o4wplL8DMf08yA5s7xQZc7PAj2Y+0dfmvjbW7RgO97j6b0nF7uOL6EvNU9Vwc6s8cFVbevowgifb9YvJU=
  on:
    tags: true
    repo: honzahommer/node-malwarepatrol
